"""inisialisasi tabel

Revision ID: 126d1d17d6ce
Revises:
Create Date: 2026-03-02 11:34:35.730917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import vector


# revision identifiers, used by Alembic.
revision: str = "126d1d17d6ce"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("nama", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "dokter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nama", sa.String(length=255), nullable=False),
        sa.Column("no_telepon", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("spesialisasi", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "dokumen",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("rawtext", sa.String(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pasien",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nomor_rekam_medis", sa.String(), nullable=False),
        sa.Column("nik", sa.String(length=16), nullable=False),
        sa.Column("nama", sa.String(length=255), nullable=False),
        sa.Column("no_telepon", sa.String(length=20), nullable=False),
        sa.Column(
            "jenis_kelamin", sa.Enum("L", "P", name="jeniskelamin"), nullable=False
        ),
        sa.Column("tanggal_lahir", sa.Date(), nullable=False),
        sa.Column("alamat", sa.Text(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nik"),
        sa.UniqueConstraint("nomor_rekam_medis"),
    )
    op.create_table(
        "chunk_dokumen",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("doc_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", vector.VECTOR(dim=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["doc_id"],
            ["dokumen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "embedding_index",
        "chunk_dokumen",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.create_table(
        "jadwal_praktik",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dokter_id", sa.Uuid(), nullable=False),
        sa.Column("hari_dalam_minggu", sa.Integer(), nullable=False),
        sa.Column("jam_mulai", sa.Time(), nullable=False),
        sa.Column("jam_selesai", sa.Time(), nullable=False),
        sa.Column("kuota_harian", sa.Integer(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "hari_dalam_minggu >= 1 AND hari_dalam_minggu <= 7", name="cek_indeks_hari"
        ),
        sa.ForeignKeyConstraint(
            ["dokter_id"],
            ["dokter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sesi_chat",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pasien_id", sa.Uuid(), nullable=True),
        sa.Column("waktu_mulai", sa.DateTime(), nullable=False),
        sa.Column("waktu_selesai", sa.DateTime(), nullable=False),
        sa.Column("summary_topik", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["pasien_id"],
            ["pasien.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pesan_chat",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sesi_id", sa.Uuid(), nullable=False),
        sa.Column(
            "sender_type",
            sa.Enum("USER", "AI", "SYSTEM", name="sendertype"),
            nullable=False,
        ),
        sa.Column("konten_pesan", sa.Text(), nullable=False),
        sa.Column("metadata_pesan", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sesi_id"],
            ["sesi_chat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sesi_konsultasi",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pasien_id", sa.Uuid(), nullable=False),
        sa.Column("jadwal_id", sa.Uuid(), nullable=False),
        sa.Column("sesi_id", sa.Uuid(), nullable=True),
        sa.Column("tanggal_kunjungan", sa.Date(), nullable=False),
        sa.Column("nomor_antrean", sa.String(), nullable=False),
        sa.Column("keluhan", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("BOOKED", "CANCELLED", "COMPLETED", name="statussesikonsultasi"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jadwal_id"],
            ["jadwal_praktik.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pasien_id"],
            ["pasien.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sesi_id"],
            ["sesi_chat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sesi_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sesi_konsultasi")
    op.drop_table("pesan_chat")
    op.drop_table("sesi_chat")
    op.drop_table("jadwal_praktik")
    op.drop_index(
        "embedding_index",
        table_name="chunk_dokumen",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.drop_table("chunk_dokumen")
    op.drop_table("pasien")
    op.drop_table("dokumen")
    op.drop_table("dokter")
    op.drop_table("admin")
    # ### end Alembic commands ###
